import React from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";

const Profile = () => {
	const { data: session } = useSession();

	return (
		<>
			<Head>
				<title>Profile</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ul className=" bg-slate-900 mx-auto flex flex-col gap-6 justify-center items-center w-1/2 py-12 shadow-lg rounded-xl text-white mt-16">
				<li className="flex items-center gap-6 w-96 rounded-lg shadow-lg bg-slate-500">
					<div className="flex justify-center items-center gap-2 rounded-l-lg bg-gray-800 w-24 p-2">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							stroke-width="1.5"
							stroke="currentColor"
							className="w-6 h-6"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"
							/>
						</svg>
						Email
					</div>
                    <span className="text-lg">
					    {session?.user?.email}
                    </span>
				</li>
				<li className="flex items-center gap-6 w-96 shadow-lg rounded-lg bg-slate-500">
					<div className="flex justify-center items-center gap-2 rounded-l-lg bg-gray-800 p-2 w-24">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							strokeWidth={1.5}
							stroke="currentColor"
							className="w-6 h-6"
						>
							<path
								strokeLinecap="round"
								strokeLinejoin="round"
								d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z"
							/>
						</svg>
						Name
					</div>
                    <span className="text-lg">
					    {session?.user?.name}
                    </span>
				</li>
			</ul>
		</>
	);
};

export default Profile;
